### ISSUE TITLE
Repositório da gem

### ISSUE THREAD

**Issue by 88patota** [brunobatista25/generate_ruby_tests#1]
Olá.
Quando tento instalar a gem, ela não é encontrada no repositório.
O erro é esse: 
ERROR:  Could not find a valid gem 'generate_ruby_tests' (>= 0) in any repository
ERROR:  Possible alternatives: generate_secrets, generate_vhosts, generated-assets, generate_lotto, generate_rc_file

**Comment by brunobatista25** [comment]
como esta instalando? em qual sistema operacional?

**Comment by 88patota** [comment]
Oi @brunobatista25 .
Estou utilizando macOS e fazendo conforme o Readme... gem install generate_ruby_tests

**Comment by brunobatista25** [comment]
estranho que aqui foi de boa tenta usar esse comando

```
gem install rubygene --source http://rubygems.org
```

**Comment by brunobatista25** [comment]
a desculpa a doc ta errada na verdade e  ```rubygene```

**Comment by 88patota** [comment]
Estava digitando isso agora, hahaha

**Comment by brunobatista25** [comment]
ja subi a correção.

**Comment by 88patota** [comment]
eu vi aqui.
muito bom o projeto.
parabéns!

**Comment by brunobatista25** [comment]
obrigado espero que goste :)
